name: Sync Infras Flow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  apply-infras:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Prepare
        run: |
          ls -al ./
          ls -al ../
          # PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          # echo $PACKAGE_VERSION

      - name: Test
        run: |
          kustomize
          echo '${{ inputs.environment }}' 
          echo '${{ secrets.VAR_A }}'
          echo '${{ vars.VAR_A }}'