name: Sync infrastructure to Dev

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/sync-infras.yml
    with:
      environment: "${{ github.sha }}-artifact"
    secrets:
      VAR_A: '123'