name: Sync Infras Flow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  apply-infras:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Test
        run: |
          echo '${{ inputs.environment }}' 
          echo '${{ secrets.VAR_A }}'